### ISSUE TITLE
мэйн пейдж

### ISSUE THREAD

**Issue by derwer5241** [rakshazi/forestguild.club#34]
Один из полезнейших классов в игре. Он может почти в любую роль. Причем, очень неплохо (кроме **танка**).

Тролли, Таурены, Таурены Крутогорья, Гоблины, Пандарены,  Орки и Орки-Маг'хары могут быть шаманами.

# [Стихии (Elemental, Рдд)](/wiki/classes/shaman/elemental)

# [Исцеление (restoration, хил)](/wiki/classes/shaman/restoration)

# [Совершенствование (enhancement, ДД)](/wiki/classes/shaman/enhancement)

**Comment by rakshazi** [comment]
Добавил, спасибо!
